@startuml sequence
skinparam handwritten true
skinparam usecase {
  BackgroundColor cornflowerblue
  bordercolor cornflowerblue
  fontColor white
}
left to right direction
actor Utilisateur as U 
actor Admin as A
actor Commercial as C
U-->(consultation catalogue)
U-->(consulter et modifier son panier)
U-->(Effectuer une commande)
U-->(Valide sa commande)
C<|-U
C-->(Edition fiche client)
C-->(Catalogue fournisseur)
A<|-C
A-->(Edition fiche commerciaux)
A-->(Consultation statistiques des ventes)
@enduml