@startuml sequence
skinparam backgroundcolor transparent
skinparam participant {
  BackgroundColor cornflowerblue
  bordercolor cornflowerblue
  fontColor white
}
skinparam actor {
  BackgroundColor cornflowerblue
  bordercolor cornflowerblue
}
actor Utilisateur as U
Participant System as S
Participant DataBase as D
U->S : clique sur l'accès direct à la boutique
activate S
S->D : récupère la liste des produits et l'adresse des images
activate D
D-->S : renvoie la liste des produit et adresse des images
destroy D
S-->U : affiche le catalogue produits
deactivate S
U->S : ajoute des produits à son panier
activate S
S-->U : rend disponible le compte d'article et l'accès au panier
note right : enregistrement du panier dans les cookies

deactivate S
U->S : enregistre son panier
S-->U : affiche la page de connection
U->S : utilisateur se connecte
activate S
S->D : recherche de l'utilisateur dans la table users
activate D
alt l'utililisateur a un compte
D-->S : valide l'existence de l'utilisateur et donne son type
S->D : enregistre la commande (en cours)
else l'utilisateur n'éxiste pas
D-->S :l'utilisateur n'est pas inscrit
S-->U : Affiche la page d'inscription
U->S : inscrit ses coordonnées
S->D : inscrit l'utilisateur dans la base
D-->S : valide l'existence de l'utilisateur et donne son type
S->D : enregistre la commande (en cours)
destroy D
deactivate S
end
S->U : demande la validation de la commande
U->S : Valide sa commande
activate S

alt utilisateur pro
S->D : sauvegarde la facture
S-->U : affiche la facture
else utilisateur particulier
S->U : demande le paiement 
U->S : effectue le paiment en ligne
S-->U : valide le paiement
S->D : sauvegarde la facture
S-->U : affiche la facture
end



@enduml
